# Generated by Django 2.1.7 on 2019-04-30 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceRequests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sent', models.BooleanField(default=False)),
                ('DateSent', models.DateTimeField(blank=True, null=True)),
                ('requestId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serviceRequests.Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('user', 'requestId')},
        ),
    ]
